# Exception
'''
try:
    ຄຳສັ່ງງຣັນໂປຣແກຣມປົກກະຕິ
except:
    ຄຳສັ່ງທີ່ເຮັດວຽກຕອນໂປຣແກຣມມີຂໍ້ຜິດພາດ    
'''

try:
    number1 = int(input('ປ້ອນໂຕເລກ 1 : '))
    number2 = int(input('ປ້ອນໂຕເລກ 2 : '))
    result = number1/number2
    print(result)
except:
    print('ໂປຣແກຣມມີຂໍ້ຜິດພາດ')

    